### PR TITLE
Try to render a usable table more quickly.

### PR DESCRIPTION
**Pull request by drewbrokke**

### CODE REVIEW

**Comment by drewbrokke** [comment]
It turns out that the _total_ render time is actually about 20ms longer on average, but the render time for just the heads is about 10ms faster, so it _feels_ faster.

**Comment by jwu910** [comment]
We should just remove danger. Lol it has been a headache and I need to spend time to actually get it working.

@kienD What do you think about this change?

**Comment by jwu910** [comment]
Just started reviewing :)

**Comment by jwu910** [comment]
@drewbrokke Sorry I never got around to this. Hopefully will make some time soon to take a look at the changes. Life changes keeping me busy

**Comment by kienD** [comment]
@drewbrokke  this is my bad too. I was supposed to look at it as well.

**Comment by drewbrokke** [comment]
@jwu910 @kienD no worries, there's no rush :)

**Pull request closed without merging**
