### PR TITLE
chore: uninstall danger.js and remove from dependencies (Issue #493)

### LINKED ISSUE #493: Uninstall Danger.js
## Description
This was never installed 100% correct and we can just point to the contributing docs for PRs that don't follow the guidelines.

We can just uninstall this dependency and remove the config files related to [danger.js](https://danger.systems/js/)

### PR DESCRIPTION
**Pull request by Jimmy-Vu**
## Description

The danger.js package is uninstalled (using `npm uninstall --save-dev danger`) from the project along with its related config files. `.travis.yml` is deleted following guidance in the [issue discussion](https://github.com/jwu910/check-it-out/issues/493#issuecomment-1437693799).

Fixes #493 
## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Documentation update

## Checklist:

- [x] I have read the **CONTRIBUTING** document.
- [x] My commits follow the [commitizen](https://github.com/commitizen/cz-cli#philosophy) commit convention
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.

### CODE REVIEW

**Comment by Jimmy-Vu** [comment]
There seems to be a problem with the lint checks (from the [lint.yml](https://github.com/jwu910/check-it-out/blob/f468e8fa5cebb5231923bac526f501a2401e5d44/.github/workflows/lint.yml) file) for when I make a pull request from the `Jimmy-Vu:CIO-493-uninstall-danger` branch in my forked repo into the `typescript-migration` branch of this upstream repo. It doesn't think that my branch exist.

Error from the prettier lint check:
```
Determining the checkout info
  /usr/bin/git branch --list --remote origin/CIO-493-uninstall-danger
  /usr/bin/git tag --list CIO-493-uninstall-danger
  Error: A branch or tag with the name 'CIO-493-uninstall-danger' could not be found
```

I found this potential fix in this [comment](https://github.com/actions/checkout/issues/455#issuecomment-1079943559) in an issue that seems to relate closely to what's occurring here. Could be worth a look.

**Comment by jwu910** [comment]
oooh thanks, i'll try to take a look when I can and get the required changes into my branch

**Review by jwu910 — CHANGES_REQUESTED** [review]
Hey @Jimmy-Vu my bad for not getting back to this sooner.

Can you take a look at the failing checks before we move forward?

Edit: This actually might be a faulty workflow file on my end... I dont think i've had any pull requests since i had merged the new workflow in myself

**Comment by Jimmy-Vu** [comment]
Hey @jwu910, thanks for the heads up. Just to confirm I understand your edit message, is there something left to do on my end for this issue or is it just waiting for the workflow file to be fixed?

**Pull request merged**
