### PR TITLE
Fixes #460

### LINKED ISSUE #460: cio --version should have an extra line break after display version number
```
Phucs-MacBook-Pro-2:dashboard phuc$ cio --version
3.0.0Phucs-MacBook-Pro-2:dashboard phuc$ 
```

### PR DESCRIPTION
**Pull request by aksappy**
#460 --version should have an extra line break after display version number

## Description
Added a line break (\n) to the process.stdout.write for --version flag

This fixes #460 

## Types of changes
- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Documentation update

## Checklist:
- [x] I have read the **CONTRIBUTING** document.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.

### CODE REVIEW

**Comment by aksappy** [comment]
@jwu910  Sure. I will do as instructed. I am sorry that we are having such a long conversation for such a small change. Happy to help and eager to learn.

**Comment by jwu910** [comment]
@aksappy Absolutely, not a problem about the length of the conversation. It's part of open source.

As you start looking to contribute to other projects, you'll find that every project has different contributing guidelines, I decided to use commitizen to try and standardize the format of the commit messages going into the codebase, and its a tool that has grown in popularity recently too.

Let me know if you have any questions! Happy to help in any way.

**Comment by aksappy** [comment]
Hey @jwu910 I just realized that I had a comment pending to be entered into this conversation. 

I have made the changes as you said. Please review when you get time.

**Comment by jwu910** [comment]
@aksappy I'm really glad you were able to get commitizen commit messages to work.

If you look at the commit log for your branch though, you're 4 commits ahead of the master branch, when it should be just one
image


Not a problem though. If you'll be patient, I can help you through this. I would like to try and keep the history pretty clean and we can achieve that through the use of [rebasing](https://git-scm.com/docs/git-rebase). 

If you want to see a little bit more about git commands, this [website](https://onlywei.github.io/explain-git-with-d3/#rebase) helped me understand a little bit more how some of the git commands affected the commit history.

What I'm expecting to see from your branch is just a single commit message along the lines of:

```
 fix(app.js): Add line break to version log
```

Please let me know if you need any help or have any questions. I am happy to answer any other questions and help you get this ticket done.

**Comment by jwu910** [comment]
@aksappy I looked at the other branch you had https://github.com/aksappy/check-it-out/commits/CIO-460-linebreak-version

And this one looks fine from what I saw. You can open a PR from your `CIO-460-linebreak-version` branch and we won't have to drop any of the merge commits.

**Comment by aksappy** [comment]
Hi @jwu910, I tried performing a rebase and went through the graphical approach. I could not get the merge commit messages out of the way. And I am now super conscious of your valuable time being lost for such a small change. I have made the change to a newly forked repo and opened a new PR # 465. I know I have not completely followed your instructions, and I am sorry about it. 

I couldn't change the branch of an existing PR, hence a new request. Hope this can be closed now.

**Comment by jwu910** [comment]
@aksappy Sorry to hear you couldn't get the commit history cleaned up. I guarantee you that my time was not wasted if you learned a little bit about pull-requests and Git.

I welcome new contributors to this project as much as possible hopefully to offer a lower barrier to entry into open source development and happy to help walk anyone through submitting a fix for something.

If you have any feedback on the documentation to help make it clearer, I welcome you to open an [issue](https://github.com/jwu910/check-it-out/issues).

Thanks!

**Pull request closed without merging**
