### PR TITLE
refactor(app.js): adds a convenience method on the state to get the current remote

### PR DESCRIPTION
**Pull request by drewbrokke**

### CODE REVIEW

**Comment by drewbrokke** [comment]
@jwu910 this pull does not add any new features or functionality. Its primary purpose is to refactor the data flow to make the intention the data and application state more clear.

Here are the big points:

#### cc5be6a  Two main data types are introduced: `Ref` and `Remote`.  
They are shaped as follows:
```typescript
type Ref = {
    active: boolean,
    id: number,
    name: string,
    remoteName: string
}
type Remote = { 
    name: string, 
    refs: Ref[] 
}
```
A `Ref` corresponds to a branch that can be checked out.
A `Remote` corresponds to a `git` remote, and contains an array of `Ref`s.

#### 006d910, e305201 All application state is moved into a state object. 
That way any references or changes to the state are obvious and explicit. This addresses a couple of case where there were shadowed variable names.

#### bac75d5 Refactor logging
Encapsulate the repetitive logging function signature by using a higher-order function to compose separate logging functions for each log even type

#### 994cbe2, 94723f8 Inline functions that are only used once
This cuts down on unnecessary indirection, which can make the intention of the code harder to understand.

Please let me know if you have any questions or comments, or if you'd like something changed. Thanks!

**Comment by jwu910** [comment]
Nuts! I really appreciate the time and effort you've put in to clean up this codebase and really explain the changes being made. 

When I started writing this, I had an idea to use a global object to manage state, but the concept was a little ahead of my time then.

**Comment by drewbrokke** [comment]
Yup, I totally get that! It's not always easy to visualize the data structures and flow when first starting a project, but it gets easier with practice!

TBH I'm not entirely certain that using a global state object is completely bug-free, but at least in this case it should make the code itself easier to read (and hopefully doesn't introduce any _new_ bugs, haha).

**Comment by jwu910** [comment]
Just started reviewing :)

**Pull request merged**
