### PR TITLE
chore(deps):  remove danger

### PR DESCRIPTION
**Pull request by KalaRaja**
remove danger and its dependencies

✅ Closes: #493

## Description

Uninstalled danger package
removed config files related to danger - dangerfile.js, dangerfile.js.sample
removed a job from Travis config that used danger package
ref #493 

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Documentation update
- [x] Refactor

## Checklist:

- [x] I have read the **CONTRIBUTING** document.
- [x] My commits follow the [commitizen](https://github.com/commitizen/cz-cli#philosophy) commit convention
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.

### CODE REVIEW

**Comment by a-camarillo** [comment]
hello, @jwu910 I can review this if needed

**Review by a-camarillo — CHANGES_REQUESTED** [review]
Hello @KalaRaja, can you please rename your commit? Per this guideline for [Semantic Commit Messages](https://gist.github.com/joshbuchea/6f47e86d2510bce28f8e7f42ae84c716) this appears to be a chore rather than a refactor

**Comment by jwu910** [comment]
Hi @KalaRaja I see we've changed the title, but can you please update your commit message as well please?

If you need help, theres lots of info at [this article](https://docs.github.com/en/pull-requests/committing-changes-to-your-project/creating-and-editing-commits/changing-a-commit-message).

**Review by jwu910 — CHANGES_REQUESTED** [review]
See comment

**Comment by jwu910** [comment]
Any update on this? May close this and bump the ticket back to todo soon

**Comment by jwu910** [comment]
Stale

**Pull request closed without merging**
