### PR TITLE
CIO-260 Added first-timers-only badge

### LINKED ISSUE #260: Add first-timers-only badge to readme
`[first-timers-only](https://www.firsttimersonly.com/)`

[first-timers-only](https://www.firsttimersonly.com/)

Add the first-timers-only badge to readme.

~~Bonus: Add the badge to the gh-pages branch as well.~~

### PR DESCRIPTION
**Pull request by devkant**
Fixes #260 
Added first timers only badge in README.md

### CODE REVIEW

**Comment by jwu910-danger** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true">Fails</th>
    </tr>
  </thead>
  <tbody><tr>
      <td>:no_entry_sign:</td>
      <td>

  :skull: Sorry! Please send all pull requests against development!
  </td>
    </tr>
  </tbody>
</table>




<p align="right">
  Generated by :no_entry_sign: <a href="http://github.com/danger/danger-js/">dangerJS</a>
</p>

**Comment by jwu910** [comment]
@devkant 	I'm changing the base branch from master to development.

In the workflow for this project, I put all my code into development until i'm ready to release a new version. Then I review and update the changelog before merging to master.

**Comment by jwu910** [comment]
@devkant Could you please check if your branch CIO-260 is up to date with development? I updated my development branch I believe after you had forked.

**Comment by jwu910** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by jwu910** [comment]
Merged, thanks!

**Pull request merged**
