### PR TITLE
Change mention of master to main in the documentation.

### LINKED ISSUE #491: Change mentions of master to main in documentation
## Description
Default branch was recently [changed](https://github.com/github/renaming) from `master` -> `main`.

We need to update our documentation to accurately represent this change so instructions for future contributions are clear.

### PR DESCRIPTION
**Pull request by CatherineNjenga**
Change mentions of master to main in the documentation.

closes #491
## Description

 Changed mentions of master to main in the documentation.

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [x ] Documentation update

## Checklist:

- [x ] I have read the **CONTRIBUTING** document.
- [ ] My commits follow the [commitizen](https://github.com/commitizen/cz-cli#philosophy) commit convention
- [x ] My change requires a change to the documentation.
- [x ] I have updated the documentation accordingly.

### CODE REVIEW

**Comment by jwu910** [comment]
Thanks for opening this PR @CatherineNjenga ! could you also please take a look at the README.md file? I believe there will be some need there as well.

**Comment by CatherineNjenga** [comment]
I updated the README.md file too, sorry about that it totally escaped my mind.

**Comment by jwu910** [comment]
@CatherineNjenga no need to apologize, just taking a quick search around the repo and see a few more references to the master branch in some links to files. I haven't deleted the master branch yet, but should probably do that soon. I could foresee those links breaking as well. Could you take a look to see if any of those could be updated as well?

**Comment by CatherineNjenga** [comment]
Sure, I updated the links that had mentioned master to main.

**Comment by jwu910** [comment]
@CatherineNjenga just want to bump. if you're still interested in getting this in, please take a look at my last comment, hope it works out! Please let me know if you have any questions

**Comment by jwu910** [comment]
Closed by https://github.com/jwu910/check-it-out/pull/522

**Pull request closed without merging**
