### PR TITLE
Typescript migration

### LINKED ISSUE #492: Feat: Upgrade to TS ➕ 🦖
## Acknowledgement 🎉 
First of all, thanks for being here. This project has always been a close one to my heart. Many thanks in advance for any contributions that are made, whether they're issues, docs, code, or just fixing typos.

## Description :construction:
This can be the placeholder ticket for the migration. How I'm understanding this now is the first step being changing the `.js` extension to `.ts`. The NPM script for the TypeScript compiler was already setup on the branch `typescript-migration` which will serve as our main feature branch we can send PRs to.

## Developing :computer:
Since we'll have dual compilers until we finish, development scripts will probably include two scripts being run in two separate sessions: `npm run watch` and `npm run tsc -- --watch`.

## Testing 🐛 
After you're set up, you should be able to run `npm start` to test your local build. If you have a global installation of `check-it-out` that you want to use the local build for, you can run `npm link` (I believe) so your global `cio` binary should link to your local output files in this repo

## Contributing 🧗🏼 
Find the [project board](https://github.com/users/jwu910/projects/7/views/1) and pick a ticket. If there's more work that has been overlooked, or we need to break any files up into smaller tickets, lets create them accordingly.

### PR DESCRIPTION
**Pull request by jwu910**
## Description

Fixes #492

Seems like everything was migrated... need to test and double check all the dep updates that went in while this was split prior to cutting a new release (or look into any other features/fixes)

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [x] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Documentation update

## Checklist:

- [ ] I have read the **CONTRIBUTING** document.
- [ ] My commits follow the [commitizen](https://github.com/commitizen/cz-cli#philosophy) commit convention
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.

### CODE REVIEW

**Comment by jwu910** [comment]
Actually i'm having issues working through tsconfigs right now to make sure we can use update-notifier, it got bumped 4 major versions in one of these PRs lol, and getting esm vs cjs errors atm

**Comment by drewbrokke** [comment]
@jwu910 any details/steps to reproduce? I'd be happy to take a look if that would be helpful.

**Comment by jwu910** [comment]
Hey @drewbrokke, that would be amazing.

So far i've seen this issue:

1. npm run build (on latest `typescript-migration` branch
2. npm link
3. cio

running `node dist/index.js` after the build is also throwing the error.

I'm thinking it has something to do with the module type and/or compile target for TS. but haven't had a chance to really dig in and research it

**Comment by drewbrokke** [comment]
@jwu910 see https://github.com/jwu910/check-it-out/pull/535.

**Comment by jwu910** [comment]
> @jwu910 see #535.

I think we're good to merge 😂 if you get a minute tomorrow, would you be able to take another pass over the changes? not sure what else we need to do, either than maybe config clean up from some of the templated files. maybe some doc updates before any release, too

**Review by drewbrokke — APPROVED** [review]
LGTM @jwu910 👍 

Did you use tooling to accomplish 41cc6e177a4e6b034e40dd68f016e51ac9857dbb? If so, is it integrated into an npm script?

**Comment by jwu910** [comment]
Lol @drewbrokke just vscode extension [Document This](https://marketplace.visualstudio.com/items?itemName=oouo-diogo-perdigao.docthis), i haven't found a way to automate this based off type annotations yet though, I know there are tools that can generate docs from jsdoc strings, just wanted to keep it uniform where i could

**Pull request merged**
