### PR TITLE
CIO-310 adding LGTM Badge to ReadMe

### LINKED ISSUE #310: Add LGTM badge to README
```
<a href="https://lgtm.com/projects/g/jwu910/check-it-out/alerts/"><img alt="Total alerts" src="https://img.shields.io/lgtm/alerts/g/jwu910/check-it-out.svg?logo=lgtm&logoWidth=18"/></a>
```

Using LGTM to track introduction of code smells and tech debt. Let's add the badge to the readme

### PR DESCRIPTION
**Pull request by Lorsen**
Fixes #310 

## Description
Adding LGTM badge image via <a> element.

## Motivation and Context

Using LGTM to track introduction of code smells and tech debt. Adding badge to readme to demonstrate that.

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

## Checklist:

- [x] I have read the **CONTRIBUTING** document.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have added tests to cover my changes.

### CODE REVIEW

**Comment by jwu910** [comment]
@Lorsen, Thanks for the PR!

I just adjusted the base branch to `development` instead of `master`.

Just a heads up, you'll want to update the PR description to say `Fixes #310` without the curlies.

**Comment by Lorsen** [comment]
Gotcha, made the change!

**Comment by jwu910** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by jwu910** [comment]
Reviewed Thanks!

**Pull request merged**
